- README.md
@jbenet as it says on the tin. :)
> Add link to clj-multicodec

- README.md
- multicodec-packed.md
> added multicodec-packed beginning

- multicodec-packed.md
As I was checking this with @jbenet, some questions appeared and this is the result of the clarifications.
> docs: improve multicodec-packed description

- table.csv
See https://godoc.org/github.com/ugorji/go/codec
> add msgpack and binc to the table

- table.csv
follows https://github.com/multiformats/multicodec/pull/35
> Torrent codes

- table.csv
> Assign a unique code to QUIC

- table.csv
Resolve [multihash#71](https://github.com/multiformats/multihash/issues/71) by adding MD4 and MD5 hashes.  See [multihash#76](https://github.com/multiformats/multihash/pull/76).
cc @lgierth @diasdavid @whyrusleeping
> add MD4 and MD5 hashes

- table.csv
> add 0x00 for multibase binary

- README.md
Updated list in readme with the haskell implementation.
> Added Haskell multicodec to the list of implementations.

- README.md
multicodec-packed isn't a thing anymore, it was what multicodec is now.
Hence remove all references to it.
> Remove references to multicodec-packed

- table.csv
Add codes for decred block and tx, in line with other cryptos.
> Add codes for Decred

- table.csv
> add dns{4,6,addr} protocols

- README.md
First pass at an Elixir implementation of Multicodec.
> Add Elixir implementation

- table.csv
I've filed issues for adding these but defining these here makes this file hard
to parse correctly.
related: #36
> remove undefined codecs

- .travis.yml
- table.csv
- validate.py
See: https://github.com/multiformats/multicodec/pull/104#issuecomment-455499679
cc @Arachnid
> Fix swarm codec conflict and add CI

- table.csv
Adds the two variations of BLS12-381 public keys.
> feat: add BLS12-381 public keys

- table.csv
Submitting PR as per issue #188, thanks in advance for your consideration.
> add / reserve KangarooTwelve in table.csv

- table.csv
- validate.py
Ref: https://github.com/multiformats/multicodec/pull/210
> Check codes are ascending with validation script

- table.csv
Corresponding spec: https://github.com/libp2p/specs/pull/325
> add libp2p-relay-rsvp codec

- table.csv
Related to https://github.com/ChainAgnostic/CAIPs/pull/50
> Add CAIP-50 to multicodec table

- table.csv
Ref: https://github.com/ipld/ipld/pull/107
> Add CARv2 IndexSorted

- table.csv
Ref: https://github.com/multiformats/multicodec/issues/242
> cid: change tag of CID entries to 'cid'

- table.csv
w3c draft here https://www.w3.org/TR/webtransport/
0x01d1
related: https://github.com/multiformats/multiaddr/pull/126
> Add WebTransport

- table.csv
spec: https://github.com/libp2p/specs/pull/412
refs https://github.com/multiformats/multiaddr/pull/131
> add certhash to multiaddr

- table.csv
See https://github.com/Jorropo/go-silverpine
Right now there is no parameters to the `silverpine` component (all it need is an Ed25519 public key which it gets from a `p2p` component later).
> feat: Add silverpine

- table.csv
Adds BeeSon support
https://github.com/fairDataSociety/beeson
> feat: beeson support

- table.csv
Fixes typo introduced in beeson pull request
> fix: typo - Swarm Feed

- table.csv
This change adds rsa-private key code since one does not seem to already exist.
> feat: add rsa private key code

- README.md
- table.csv
As per #289 this pr proposes to register common signature algorithms used in [UCAN](https://github.com/ucan-wg/spec/)s.
> Propose codes for signature algorithms

- table.csv
See https://github.com/multiformats/multiaddr/pull/150#issuecomment-1468791586 for context.
> fix: Rename webrtc-w3c to webrtc and webrtc to webrtc-direct

- table.csv
This PR adds the BLS12-381 private key entries.
> Add BLS12-381 private key entries

- table.csv
Add ML-KEM public keys, as specified by FIPS-203: https://csrc.nist.gov/pubs/fips/203/final
> Add ML-KEM public keys as specified by FIPS 203

- README.md
> Add Zig impl

- README.md
Ref: https://github.com/multiformats/multicodec/issues/373
> docs: describe tags in the table
