- README.md
I believe that the question “Which one of these is the encoder and which the decoder?” becomes really deep when `5555 <---[ THING ]---- 5555` is presented as one of the examples.
That THING does not seem to encode and decode anything. A fan of zen might call it 無駄、 a workless work.
Such revelation is really enlightening but it probably carries the wrong message and that example should actually mirror the previous `5555 ----[ THING ]---> 8888` instead of its current form.
> the `5555 <---[ THING ]---- 5555` revelation is too enlightening

- README.md
Keccak-256 is required for ethereum canonical hash support.
Keccak and SHA3 are related. SHA3 is built on top of Keccak.
see https://en.wikipedia.org/wiki/SHA-3#Instances for how SHA3 parameterizes Keccak.
```
keccak-224 0x1A
keccak-256 0x1B
keccak-384 0x1C
keccak-512 0x1D
```
> Add keccak-*

- table.csv
Blake2s and Blake2b have different initial vectors states for different lengths, this means that for each chosen output length it looks like completely different hash function.
This proposal allocated 64 values for Blake2b and 32 values for Blake2s as those are the ranges the outputs can be chosen from.
Those codes will require 3 bytes to write down as varints.
> Add blake range codes

- table.csv
Here are the Ethereum objects as I have mapped them so far. While there are only two underlying structures (RLP and Eth-(Secure-)Trie), they interpret the format of the leaf values based on context, which is lost when resolving at the IPLD level. I sketched out some versions that used fewer IPLD formats by employing some cleverness in the path naming conventions. (see here https://github.com/MetaMask/metamask-plugin/issues/719#issuecomment-267528294). The consensus was to be explicit instead of clever, thusly the list of objects as I've proposed.
I'd additionally like to reserve 0x99-0x9f for additional Ethereum objects I may have missed or may be introduced when Ethereum milestone Metropolis is released.
> Add eth-objects

- table.csv
Adds BitTorrent [info metadata](http://www.bittorrent.org/beps/bep_0003.html#info-dictionary) format as `0x7b`. (Mnemonic: `B7` for <b>B</b>it<b>T</b>orrent, but transposed so the value remains one byte after [unsigned-varint](https://github.com/multiformats/unsigned-varint) encoding.) Also adds [BitTorrent's bencoding](http://www.bittorrent.org/beps/bep_0003.html#bencoding) under serialization formats, but leaves it unassigned for now.
I'm working on some software that includes a web gateway for distributed content. It will initially only serve content from BitTorrent torrents, but I'd like to eventually include interlinked IPFS content, so I intend to move to a path scheme that's as similar as possible (ideally the same/compatible) as that used by IPFS/IPLD/CIDv1.
As a first step I …
> Add BitTorrent info metadata format as 0x7b

- table.csv
See https://github.com/ipfs/notes/issues/241#issuecomment-296392217
I suggest using the code `0xed` so that's it's visually obvious and easy to remember it's associated with ed25519.
> Add ed25519 public key codec

- table.csv
I was looking for the CBOR prefix in this file, but couldn't find it here,
found it (and protobuf) in https://github.com/multiformats/js-multicodec/blob/master/src/base-table.js
so I assume those values are up to date, and belongs in this table also?
> Update table.csv: codes for CBOR and Protocol Buffers

- table.csv
By raw it means uncompressed - git by default stores deflated objects, but their hash is calculated before compression.
> Add git-raw codec

- table.csv
not sure if there is a code for `base2` (ascii 101010101) yet but it is incorrectly set to the same as "raw binary"
> remove incorrect base2 code

- README.md
- table.csv
This extends the concept of multicodecs to general symbolic (text) strings, not just byte strings.
replaces #59
@diasdavid I've changed multibase prefixes to be "symbolic". Thoughts?
TODO: Deprecate 0x55 or 0x0? Having both is a bit annoying. They both mean "raw
binary data".
> fill out multibase table and treat multibases as symbols

- table.csv
Adding `dag-json` to codec table.
See #80 for discussion.
> feat: add dag-json, fixes #80 

- table.csv
Can be prefixed to the "ip6" protocol. See [rfc4007].
[rfc4007] https://tools.ietf.org/html/rfc4007
> table.csv: Add "zone" multiaddr (IPv6 zone)

- README.md
Due to the removal of references to multicodec-packed in commit
[888cc045de9ea668ec2b098c00173a5eb886b0f8] the first question
doesn't make any sense anymore.
[888cc045de9ea668ec2b098c00173a5eb886b0f8]: https://github.com/multiformats/multicodec/commit/888cc045de9ea668ec2b098c00173a5eb886b0f8
> Remove questions that didn't make sense anymore

- README.md
There are already multicodec codes in the table which are > 127
(Blake and Stein hashes). Hence implementations need to implement
varint.
> Remove implementation note

- table.csv
* onion3 is for v3 onion addresses
* garlic64 is for *full* i2p addresses. We may later need a garlic32 for "short" garlic addresses.
See: https://github.com/multiformats/multiaddr/pull/77
cc @eyedeekay
> add oinion3 and garlic64 protocol codes

- table.csv
Also, rename ipfs to p2p as the *canonical* name.
> copy missing codecs from the multiaddr repo

- table.csv
Make it clearer (and easier to convert) that dag-json is two bytes.
> Write dag-json codec as two bytes

- table.csv
Also rename the existing `murmur` to `murmur-128`.
> Add murmur3 32-bit

- table.csv
As discussed in https://github.com/multiformats/multiaddr/issues/73 and offline.
> Add CIDs for IPFS and Swarm

- validate.py
Many installations have python3 installed elsewhere, such as /usr/local/bin/, etc.  Use the environment PATH variable to locate, using /usr/bin/env.
> Use '#!/usr/bin/env python3' vs. fixed path '/usr/bin/python3'

- table.csv
Holochain is an open source framework for building fully distributed, peer-to-peer applications.  See https://holo.host for more background.
We will be launching in the next few months, and would like our Holochain node Addresses to have the 0x86 prefix, if possible.  That, along with our 70-byte long core keys+parity data will result in a multicodec prefix of 0x8646.  When base-64 encoded, this yields Addresses with prefix "hkZ...", which is useful for our users to help them quickly identify potential Holochain Addresses.
Thanks for your consideration!
> Add several varint prefix codes + lenghts for Holochain IDs

- table.csv
Hi,
I'd like to add these two Swarm primitive types that we'd like to be able to reference from ENS resolver contracts.
Please let me know if I should shift the codes around (although obviously lower numbers = less data on chain).
Cheers
> Add Swarm multicodecs

- table.csv
That way, we can always tell if something is a path or something else.
We may also be able to take advantage of this later to combine a few
concepts and get rid of the "multiaddrs look like paths but are totally not"
problem. However, we can think about that later. This PR just reserves the code
so we don't run into problems later.
* Remove the distinction between string/binary multiaddrs. Instead, the "string"
will *also* be a valid binary multiaddr.
* Define a new multipath spec to combine multiaddrs and other paths.
Related to: https://github.com/multiformats/multiaddr/issues/70
> reserve 0x2f (ASCII /) as the *path* multicodec

- table.csv
This goes with the other I2P base32 pull requests, it adds i2p base32 addresses and adds descriptions of what the I2P Addresses are to the table.
> Add garlic32, describe garlic addresses

- table.csv
- validate.py
This commit normalizes hexadecimal syntax of codes to lowercase and ensures that uppercase and lowercase will not be mixed again.
> Normalize hexadecimal syntax of codes

- table.csv
This is specifically for the protobuf-encoded libp2p key format:
```proto
enum KeyType {
RSA = 0;
Ed25519 = 1;
Secp256k1 = 2;
ECDSA = 3;
}
message PublicKey {
required KeyType Type = 1;
required bytes Data = 2;
}
```
Required for converting a peer ID into a CID (for base32-encoded IPNS).
fixes #130
> multicodec: add IPLD codec for libp2p public keys

- README.md
I've implemented this as proposed in #134, which means that the ruby implementation is just that: a table with some convenience. Currently it would be up to the ruby versions of cid (wip) and outdated ruby multihash to use these tables and add/intepret the prefixes.
> Add Ruby implementation

- table.csv
Add an IPNS namespace.  This will have the same format as IPFS but allow resolution of IPNS paths.
> Add IPNS namespace

- table.csv
Add [ZeroNet](https://zeronet.io/) site address to protocol codes. ZeroNet uses old-style Bitcoin addresses as site addresses.
> Add ZeroNet site address

- table.csv
Alternatively, we could repurpose https (443) as TLS and define HTTPS to be `/tls/http` (which is, IMO, more correct).
But let's make this decision quickly. I'm fine keeping this as it is and later deprecating `/https` in favor of `/tls/http`.
> add a TLS multicodec

- README.md
Multicodec changed over time what it actually is. The README should reflect
the current state on how it is used.
Closes #133.
Please see this as a starting point we can hopefully find agreement on. Please
also help to rephrase my changes into better English (I couldn't get rid of overusing
the word "use").
> Make README reflect what multicodec currently is used for

- table.csv
[SM3](https://en.wikipedia.org/wiki/SM3_(hash_function)) is a very popular hash function in China. Add it to table.
> add gm sm3-256 multihash to table

- table.csv
BLAKE3 is a fast cryptographic hash function. It is only one algorithm with no variants. See https://github.com/BLAKE3-team/BLAKE3 for details.
> Add entry for BLAKE3 with 256-bit output (default)

- table.csv
It would be great to have the ability to reserve ranges in this table. I'd like to reserve the `[0x0300,0x03ff]` range for libp2p.
In the context of https://github.com/libp2p/go-libp2p/issues/776.
> add 0x0301: libp2p-peer-record mapping.

- table.csv
The decentralized identity community is using DIDs as their foundation layer, i.e., implementing a decentralized PKI system. did:key is one specific DID method and is using multibase/multicodec to express the method-specific-identifier of their DIDs. Currently, there is only support for ed25519-pub but the DID community uses secp256k1 also extensively. In order to use secp256k1 with did:key, we need to get support for secp256k1-pub.
> add support for secp256k1-pub

- table.csv
Add support for X25519 public keys (for use with Key Agreement Keys etc).
> Add X25519 (Curve25519) pub key support

- table.csv
See discussion here: https://github.com/ipld/specs/issues/251
> Add dag-jose, -cose

- table.csv
SHA2-256 with the trailing 2 bits zeroed out. Primary current use is Filecoin.
It's only "truncated" in the sense that the output is truncated, but there are the same number of output bits.
`0x1012` was chosen to mirror the `0x12` sha2-256 entry and it's close to some other, less common, hash functions.
Current implementations:
* https://github.com/filecoin-project/rust-fil-proofs/blob/ac49ce4111f0bbbb6bec3d6cc2d58d60c48487dd/storage-proofs/core/src/hasher/sha256.rs#L74-L79
* https://github.com/rvagg/js-fil-utils/blob/52255d1603ac49d912d8a1ede66bab5c0baa228b/merkle.js#L5-L12
Ref: https://github.com/multiformats/multicodec/pull/161
> add sha2-256-trunc2 multihash: 0x1012

- table.csv
Reserving the 0xb400 range for Poseidon variants. These entries allow FIL to iterate on the `fcX` extension of the name where they stay with BLS12-381 and arity=2. High security variant is for extra circuits that are usable in case new attacks arise from the standard variant.
* The primary ways of differentiating Poseidon implementations are curve and arity, hence their encoding in the name.
* There are additional parameters, hence the need for an extra differentiator `fc1`.
* Filecoin may change these additional parameters in future versions, and therefore need to differentiate and iterate on the `fcX` extension.
* When parameters are initially generated, extra circuits may also be generated, providing a high security, but more costly, variant at the same time. Hence the `sc` addition. …
> Add two Poseidon Filecoin variant multihashes

- table.csv
These only describe the roots of a merkle tree, not the underlying data. In the case of CommP and CommD they are binary merkle trees using sha2-256-trunc2. For CommR they are novel structure merkle trees using poseidon-bls12_381-a2-fc1.
All nodes of the respective merkle trees could also be described using this codec if required, all the way to base data. It is anticipated that the primary use will be restricted to the roots.
This PR partly assumes #170 and #171, although it would be possible to use `identity` multihash with these to form a CID. It does depend on agreeing that our approach to merkle tree "hashing" wrt multihash is that we identify individual nodes, rather than treating the entire merkle process as a "hash function". So in the case of CommP, the CID we'd generate …
> add filecoin commitment merkle root codecs

- table.csv
As proposed in #117, there are no definitions for the ripemd family of hashes.
The previous PR would have been sufficient with the given feedback, but the author never made the requested changes and the PR is now over a year old.
This PR would replace #117.
It conforms to feedback on #117, with the more common ripemd-160 hash using the one byte space and the less common algorithms using the two byte space.
0x52 was chosen somewhat arbitrarily as the ASCII encoding of 'R'.
Furthermore, 0x51 is the serialization code for CBOR, which means 0x52 is unlikely to be needed as a value in relation to CBOR.
> Add ripemd definitions

- table.csv
This completes the set needed to interact with the full Bitcoin graph with IPLD. The Witness Commitment is the link to the second binary merkle that contains the transactions with full witness data, whereas the initial binary merkle pointed to from the block header (known as `merkleroot`) points to the transactions without witness data. Since SegWit, this second binary merkle tree gets linked to from the coinbase `scriptPubKey` property and the coinbase is excluded from the binary merkle (replaced with `0x000...000`) as a result. The reason we need this new element is that the coinbase points to an intermediate structure which concatenates a nonce and the new `merkleroot` together and the nonce, in the standard representation, becomes the "witness" property of the coinbase itself. So to …
> Add Bitcoin Witness Commitment (0xb2)

- table.csv
Adds an additional well-known format to the table.
0xcert Asset Imprints. This is a Merkle tree structure which is used to hash and identify arbitrary-depth objects (generally from JSON). This is an open specification.
Following is some documentation for reference and your consideration of this pull request:
- Overview: https://github.com/0xcert/framework/blob/master/packages/0xcert-cert/README.md
- Documentation: https://docs.0xcert.org/api/guides/update-asset-imprint.html#usage-overview
- Reference implementation: https://github.com/0xcert/framework/tree/master/packages/0xcert-cert
> Add 0xcert asset imprints

- README.md
- table.csv
- validate.py
Ref: https://github.com/multiformats/multicodec/issues/181
Ref: https://github.com/multiformats/multicodec/pull/177
/cc @bonedaddy @fulldecent 
I agree with @bonedaddy on this one, it's awkward for `0xcert` but they kind of chose an intentionally awkward name, I bet their code has issues with constant naming.
@fulldecent can you live with this rename or does this violate something fundamental about `0xcert`?
> Naming restrictions (doc & validate), rename `0xcert` to be code-friendly

- table.csv
This PR adds CIDv1 as a multicodec with value `0x01`. 
Fixes https://github.com/multiformats/multicodec/issues/49
> Define CIDv1 as a mutlicodec

- table.csv
https://www.iana.org/assignments/jose/jose.xhtml#web-key-elliptic-curve
```
p256-pub,                       multihash,      0x1200,         P-256 Public Key
p384-pub,                       multihash,      0x1201,         P-384 Public Key
p521-pub,                       multihash,      0x1202,         P-521 Public Key
ed448-pub,                      multihash,      0x1203,         Ed448 Public Key
x448-pub,                       multihash,      0x1204,         X448 Public Key
```
> Add JSON Web Key Elliptic Curves from IANA

- README.md
- validate.py
See GH/multiformats/multicodec#158. Changes are analogous to those proposed in GH/multiformats/multicodec#159.
> Add reserved code range for private use by applications

- table.csv
This adds a code for Ed25519 secret keys.
Ed25519 public keys have been previously added (https://github.com/multiformats/multicodec/pull/46).
Secret keys don't need to be shared as often as public keys, but there are valid use-cases and it also makes sense to have a multicodec code for internal storage of keys.
> Add ed25519 secret key codec

- table.csv
For certain signatures such as https://github.com/mattrglobal/bbs-signatures it is useful to have a single private key have a corresponding public key in both the G1 and G2 fields.
> Add BLS 12-381 g1 and g2 public key concatenated identifier

- table.csv
Adds an entry for Ceramic Document Ids, as `0xce`. I think this would be a `namespace`, but let me know if it should be something different!
See how it's used: https://github.com/ceramicnetwork/CIP/issues/59
> Add Ceramic Document Id

- table.csv
This PR adds a Skynet codec to ultimately add ENS support for Skylinks.  
Skynet is a decentralized CDN built on top of the Sia network, find out more [here](https://siasky.net/).
> Add Skynet codecs

- table.csv
The thread protocol is now relatively well-recognized in the community. Perhaps its time to make it official?
> Adds Textile Thread multiaddr

- table.csv
Naming of the Ceramic document identifier has been changed to streamid.
https://github.com/ceramicnetwork/CIP/blob/main/CIPs/CIP-59/CIP-59.md
> Rename Ceramic docid to streamid

- table.csv
Reasoning:
There already exists and ed25519 priv key: https://github.com/multiformats/multicodec/blob/master/table.csv#L128
Without the ability to represent both public and private components of asymmetric key pairs users will be forced for do things like this:
```
'id': '',
'type': 'EcdsaSecp256k1VerificationKey2020',
'controller': 'did:example:123',
'publicKeyMultibase': 'zQ3shU9mxTYfMTLceuppoNM5siowHvw3xBk21r855kwgNHNAX',
'privateKeyBase58': '6GyEn649EsbEEJXGQ5m8Eq6NANDmHTPQPWGyF5uL7kx8'
```
This prevents efficient compression using multibase codecs.
We will likely need to add entries for NIST curves and BLS12381 as well.
> Add secp256k1 private key

- table.csv
The affected curves can be represented in both a compressed and an uncompressed format. This clarifies that the compressed format should be used.
> Clarify public key encodings

- table.csv
Analogous to https://github.com/multiformats/go-multiaddr/pull/153, we also want to be able express Noise addresses, e.g. `/ip4/127.0.0.1/tcp/4001/noise`.
cc @mxinden
> add a Noise codepoint

- table.csv
In our IPLD representation of the Ethereum Merkle data structure, we would like to compose the logs contained in a receipt into a "log trie" that is linked to from the receipt. We want to Merkleize them in a manner analogous to how transaction and receipt lists canonically are: composing them into a Modified Merkle Patricia Trie (MMPT), whereby the RLP encoded log is the value stored in a leaf node and the path to that leaf node is the keccak256 hash of the log's index in the receipt.
We are not changing the binary encoding of a receipt IPLD- that remains the consensus encoding of a receipt- we only want to change the in-memory materialization of that binary data so that a receipt IPLD node links to the root node of a log trie.
Implementations of the new log and log trie codecs and the …
> log and log trie multicodec types

- table.csv
See
https://docs.softwareheritage.org/devel/swh-model/persistent-identifiers.html
for the technical details of that spec.
Software Heritage has done a superb job promoting content addressing in
general, and their identifier scheme (SWHIDs, for short) in particular.
By supporting them in CIDs / IPLD, I hope the IPFS ecosystem can align
itself with that effort.
Per the linked documentation, SWHIDs have their own nested grammar and
versioning scheme. I begun by taking the version 1 core identifier
grammar, unrolled it, and replaced `:` with `-` per the guidelines on
separators, with the result being these 5 rows.
There is overlap between the remaining for and git-raw, so this just
adds SWHID snapshots for now.
> Add SoftWare Heritage persistent IDentifier snapshots

- table.csv
Add RSA public key. Updated over https://github.com/multiformats/multicodec/pull/195
Changed from #195:
* Move to `0x12XX` range
* Added X.509 directly to the name (happy to take out)
RSA is has length variants, I suppose that we're going to use multiformats to specify key length. Alternately, we could specify rsa-2048-pub, rsa-4096-pub, and so on, but it feels orthogonal _to me_.
Thoughts or changes @b5?
> Add RSA public key

- table.csv
Define a new codec for CARv2 `MultihashIndexSorted`.
See:
- https://github.com/ipld/go-car/pull/217
- https://github.com/ipld/go-car/issues/214
> Add CARv2 `MultihashIndexSorted` codec

- table.csv
Add common symmetric keys. We have a use case for storing & (securely) transmitting symmetric keys to encrypted data on IPFS.
I didn't split out `-CBC`, `CTR`, `-GCM`, and so on because those are modes of operation, not the actual keys. AFAICT this also extends to XChaCha, which only accepts 256-bit keys but the contents of that 256-bit key is the same. We _can_ add the operation modes to the format, but _to me_ that feels like it belongs on the encrypted data, not on the key.
If we take the reasoning above to the extreme These are all random bits. In theory we could just have "256-bit symmetric key". Flagging the intention of the key feels right here ("oh this is a ChaCha key!") more than the operation mode did. But again, please let me know if you disagree!
AES starts with "A", and is …
> Add AES & ChaCha keys

- table.csv
Analogous to #221.
As we want to stop negotiating security protocols, we'll also need a codepoint for insecure connections. Example: `/ip4/1.2.3.4/tcp/4001/insecure`.
> add a codepoint for plaintextv2

- table.csv
This PR is to change the `rsa-x509-pub` (`0x1205`) entry to use `RSAPublicKey` (instead of `SubjectPublicKeyInfo`), and to rename it to `rsa-pub`.
This is to have a more compact and unambiguous key representation, and greater consistency with the other public key types, by removing the wrapper data structure that includes an algorithm identifier.
@b5, @expede (and anyone else): are you already using the current `rsa-x509-pub`/`0x1205`, such that this would break your existing installations and credentials?
If so, we could probably use a new code instead of changing this one. But I think it would be useful to have somewhat of a canonical representation of the key type in the table. Also, backwards compatibility with the previous usage would be possible, as these two representations are …
> Use RSAPublicKey in 0x1205

- table.csv
Per discussion in https://github.com/multiformats/multicodec/issues/205 ,
and further discussion of the numbers,
in https://github.com/multiformats/multicodec/pull/206 .
Most of the variants are shifted into larger number ranges.
> Add missing variations of sha2

- table.csv
0x22 is currently used widely through IPFS as representing the `murmur3_64` length. This makes the table match reality, and allocates 0x24 for the 128 bit length.
> update murmur3 length / family to match current uses

- table.csv
This change moves us toward the "ipld" tag meaning something like "can logically be used as a codec code in a CID"; with the recognition that this is a bit squishy and there is some amount of gentle abuse around the edges of CIDs which we willingly turn a blind eye to.
Ref: https://github.com/multiformats/multicodec/issues/242
Ref: https://github.com/ipfs/go-ipfs/issues/8471
> json,cbor: switch to "ipld" tag

- table.csv
[Subspace Network](https://subspace.network/) is a blockchain with novel Proof-of-Archival-Storage consensus that is designed to bloat massively.
It has ability to store archival data (and [already does](https://www.parity.io/blog/subspace-archiving-kusama-with-onfinality) on testnet), thus needing a way to address contents in different ways.
This is a request to reserve a namespace similarly to Arweave such that we can use multicodec in future-proof way.
> Add subspace namespace

- table.csv
Add a code for CARs so that in .storage services we could identify them by multihash
> feat: add code for car serialization format

- table.csv
These will be signalled through e.g. the metadata sent to indexers for signalling howa provider can provide CIDs
> Define transports for use in signalling protocols

- table.csv
The ISCC is similarity preserving identifier for digital content. An ISCC is derived algorithmically from the digital content itself, just like cryptographic hashes. However, instead of using a single cryptographic hash function to identify data only, the ISCC uses a variety of algorithms to create a composite identifier that exhibits similarity-preserving properties (softhash). For an implementation of code `0xcc01` see: https://core.iscc.codes/#quick-start
> Add ISCC to multicodecs table

- table.csv
SM2 is a set of cryptographic algorithms based on elliptic curve cryptography, including a digital signature, public key encryption and key exchange scheme.
> add SM2 pub key.

- table.csv
This introduces an entry to the registry for a multihash that represents a SSZ Merkle root using a SHA2-256 hash function. SSZ is a serialization and Merkleization process that is used extensively in the Ethereum Beacon chain.
The SSZ specification is described in detail here: https://github.com/ethereum/consensus-specs/blob/dev/ssz/simple-serialize.md#simpleserialize-ssz.
> Reserve multihash type for ssz-sha2-256

- table.csv
This is an ongoing pain-point because it serves as an example of the very weird edges of the multicodec table. I'm not aware of any real use; or even how it could be practically used. It's not a "hash function", but describes a hash process that needs additional "function" information. I suspect it has its genesis in looking at Bitcoin et. al., but for those binary merkle trees we use `bitcoin-tx` coupled with `dbl-sha2-256` which gives us all the information we need.
`ssz-sha2-256-bmt` is a newer example of an entry that's more descriptive, it stretches definitions a bit here but describes a hashing process within a format. It's probably not an awesome example either, but it's closer to a standard (current) understanding of multiformats than `bmt` is (not just because it can actually be …
> remove bmt entry

- table.csv
Rationale:
- been around since  the very early days, seems we just never added it because `/ipns/` was good enough for existing use cases 
- we already have dnsaddr, which works similar way, but for multiaddrs  (TXT records), adding dnslink removes the uncertainty if someone wants to use codec to distinguish between the two
- cc @Stebalien in case I am missing any reason we should not have this as a codec
- we want to support DNSLink chaining without `/ipns/` in TXT records, so it is useful for non-IPFS use cases
-  `dnslink=/dnslink/example.com` 
- (we had to remove mentions of it https://github.com/ipfs/ipfs-companion/issues/1039 for now due to ambiguity and lack of support in our stack, this PR will enable us to close this gap)
- we want a clear way for pinning DNSLink names within …
> add dnslink namespace

- table.csv
- validate.py
Previously, we called these foo-ns. Now we just call them foo (the fact that they're "namespaces" is implicit.
This way, the path component always matches the multicodec name (for both multiaddr and other path types).
> rename namespaces and remove "ipfs" alias for "p2p"

- table.csv
Adds a new `canonhash` tag value that represents a combination canonicalization+hash operation (using RDF Dataset Canonicalization URDNA2015, soon to be renamed to URDCA2015).
Used for the hashlinking of Verifiable Credentials proposal to the W3C VC WG, in the implementation of `digestMultibase`.
`digestMultibase` example:
```
MULTIBASE('base58btc', CANONICALIZE('urdca-2015-canon', MULTIHASH('sha256', <canonicalized input>)))
```
```
MULTIBASE('base58btc', CANONICALIZE('jcs-canon', MULTIHASH('sha256', <canonicalized input>)))
```
> Add 'jcs' and 'urdna2015' canonicalization values.

- table.csv
See https://github.com/multiformats/multiaddr/issues/145 for a detailed explanation.
Implementations MAY choose to continue accepting `/quic` multiaddresses (and interpret them as `quic-draft29` or `quic-v1` at their discretion).
---
cc @elenaf9 @thomaseizinger, who are apparently not part of the multiformats org yet.
> add a new QUIC codepoint for QUIC v1

- table.csv
This PR adds the `0x0d` code for representing a [multidid](https://github.com/ChainAgnostic/multidid/pull/2). 
Picked a quite low number, which seems reasonable given the possible future prevalence of DIDs.
> Add multidid code

- table.csv
I'm not too sure on the naming, sources:
- https://cyan4973.github.io/xxHash/ lists XXH32, XXH64, XXH3_64bits and XXH3_128bits
- https://github.com/Cyan4973/xxHash/ lists XXH32, XXH64, XXH3, XXH128
So I went with xxh-32, xxh-64, xxh3-64, xxh3-128 to align with the formatting of the rest of the table
> Add xxHash

- table.csv
JSON Web Key (JWK) has required members and optional members, the member's order is undefined due to JSON Object representation. The PR proposes a codec for all JWK types, which yields to a deterministic output.
> Add jwk-jcs

- table.csv
~~`identity` and~~ Murmur3 hashes changed to `hash`, per multiformats/multihash#157.
> Re-label Murmur3 as non-cryptographic hash functions

- table.csv
This PR proposes adding `ipns-record`, like we already have one for `libp2p-peer-record`.
Rationale / potential uses:
-  Main one: we should add a dedicated codec for IPNS Record, otherwise people will use `ipns`(0xe5) code which would be invalid, as it indicates IPNS "namespace".
- [IPIP-351](https://github.com/ipfs/specs/pull/351)  will ship in Kubo 0.19 and will allow fetching signed (verifiable) IPNS Record.
- In the future `/ipns/{id}?format=car` could return a CAR with `ipns-record` as an additional block.
- IPNI wants to support IPNS Records, but need codec (https://github.com/ipni/specs/pull/4)
> Add IPNS Record code

- table.csv
Schnorrkel/Ristretto x25519 ("sr25519") is a schnorr signature scheme on [Ristretto](https://ristretto.group/) compressed ed25519 points used in [Substrate](https://github.com/paritytech/substrate) framework.
You can find more information:
- Schnorrkel: https://github.com/w3f/schnorrkel
- Ristretto: https://ristretto.group/ristretto.html
> Add sr25519

- table.csv
This PR adds multicodec table entries for private keys of ecdsa curves P-256, P-384, and P-521.
> adds multicodec table entries for private keys of ecdsa curves

- table.csv
Adding `aes-gcm-256` multicodec. Please edit if the category `encryption` doesn't fit here.
`aes-gcm-256` is a payload format: the 12-byte Initialization Vector (IV) is concatenated with a payload encrypted using AES in Galois/Counter Mode, using a 256-bit key and the 12 byte IV.
This multicodec is required for the Double Hash DHT https://github.com/ipfs/specs/pull/373
> Adding multicodec for aes-gcm

- table.csv
Adds the webrtc-w3c multiaddr protocol based on the following spec: https://github.com/libp2p/specs/pull/497
> feat: add webrtc-w3c

- table.csv
per the trustless gateway spec
The exact semantics of this spec are evolving, but might as well reserve a code that we can use for indicating the existence of an HTTP endpoint for index providers.
> Add a transport code to indicate content is provided via car

- table.csv
Hey all 👋 We ended up wanting a LOT more flexibilty in Varsig than a codec tag, and broke it out into its own spec here: https://github.com/ChainAgnostic/varsig
This is essentially `multisig`, except that sequence of letters has a widely-used namespace conflict in multisig wallets. To avoid confusion, it's "varsig", but almost certainly belongs in the block with the other multiformats.
If useful, we can remove the previously-added `draft` signature types from this table, but I know  historically there's been resistence to that. I'm happy either way 👍
> Add Varsig Multiformat

- table.csv
We'd like to upstream libp2p support for the [SCION](https://scion-architecture.net) Internet architecture. As a first step, this PR reserves a code for SCION multiaddrs like `/scion/19-ffaa:1:1079...`.
> Add code for SCION multiaddrs

- table.csv
This PR adds sha256a which is an associative hash function. It's defined as the sum of multiple sha2-256 hashes.
You can read the [specification here](https://cips.ceramic.network/CIPs/cip-124#sumofsha256s).
> Add sha256a

- table.csv
This is to allow representing Secure Scuttlebutt addresses in MultiAddress format
> Adding a multiaddress key for SSB

- table.csv
The [W3C RDF Dataset Canonicalization and Hash Working Group](https://www.w3.org/groups/wg/rch) has decided that the name of the algorithm should be RDFC-1.0. We therefore request that this be updated in this table.
See these links for more context:
- https://www.w3.org/2023/06/07-rch-minutes.html#r01
- https://github.com/w3c/rdf-canon/issues/88
- https://github.com/w3c/rdf-canon/pull/116
> Rename urdca-2015-canon to rdfc-1-0

- table.csv
Registering prefixes for Amazon S3's parallel SHA2-256 with fixed 5MB or 8MB blocks
(the ones they actually implement in their SDK, and for which we are building a compatible implementation.
> #342 Amazon S3's parallel SHA2-256 with fixed 5/8MB blocks

- table.csv
This adds a codec for hash sequence blobs used by Iroh.
Docs describing hash sequence blobs: https://iroh.computer/docs/layers/blobs#collections
> add `iroh-hashseq` codec

- table.csv
The multicodec corollary to https://github.com/multiformats/multiaddr/pull/164
closes #324
> Add http-path

- README.md
Hi,
copper-multicodec is an open-source implementation of multicodec format in Java. The latest 1.0.0 release includes up-to-date codecs.
Thank you!
> Add copper-multicodec Java implementation

- table.csv
This adds a number of multicodec values for various Cryptid projects ahead of the public release of the code. Most of the code is already available:
* [Multicid](https://github.com/cryptidtech/multicid)
* Contains the VLAD implementation. [Spec](https://github.com/cryptidtech/provenance-specifications/blob/main/specifications/vlad.md)
* [Multisig](https://github.com/cryptidtech/multisig)
* [Spec](https://github.com/cryptidtech/provenance-specifications/blob/main/specifications/multisig.md) 
* [Multikey](https://github.com/cryptidtech/multikey)
* [Spec](https://github.com/cryptidtech/provenance-specifications/blob/main/specifications/multikey.md)
*Contains the Nonce implementation as well. [Spec](https://github.com/cryptidtech/provenance-specifications/blob/main/specifications/nonce.md)
> add Cryptid codecs

- table.csv
The poseidon bls12 entries already exist to mark this convention and we have a note in the README that calls this example out specifically.
Ref: https://github.com/multiformats/multicodec/pull/291
Ref: https://github.com/multiformats/multicodec/pull/361
Ref: https://github.com/multiformats/multicodec/issues/356
---
I only noticed this discrepancy when looking at #361.
@expede is this gong to hurt anyone that you know of if we change this
> fix: rename bls-12381* to bls12_381* for consistency

- table.csv
We already have the encoding of the SM2 public key(https://github.com/multiformats/multicodec/pull/267), and now we need to add the encoding of the SM2 private key.
> add SM2 priv key.

- table.csv
Add CIDs used for the [Shelter protocol](https://shelterprotocol.net)
> Add Shelter protocol CIDs

- table.csv
This PR reserves a single multihash code. The request here comes from the Filecoin ecosystem which is already using the underlying hashes here in relation to the codes reserved in https://github.com/multiformats/multicodec/pull/170 and https://github.com/multiformats/multicodec/pull/172.
However, it turns out the approach taken in the reservation of those codes was insufficient and as a result there’s a new [spec proposal](https://github.com/filecoin-project/FIPs/pull/758) for a different multihash to better represent the data being referred to.
At a high level there were three approaches for describing these trees given [here](https://github.com/multiformats/multicodec/pull/161#issuecomment-614429691). We went with option 2, but that turns out to have been a mistake so now we’re going …
> add fr32-sha2-256-trunc254-padded-binary-tree multihash

- table.csv
Intended for IPNI registrations: provider X has piece Y available on `transport-filecoin-piece-http`
> Add transport-filecoin-piece-http

- table.csv
This PR proposes a new multicodec entry for the canonical binary representation for X.509 certificates, as defined in [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280#section-4.1), encoded in DER form.
- This covers exactly one Certificate object; if there’s demand for transporting multiple certs, CRLs, OCSP responses, or PKCS#7 bundles, those should be proposed as separate, unambiguous entries.
- Version is not restricted to v3 — v1 and v2 certificates are valid encodings and will parse under the same ASN.1 type.
- Consumers can unambiguously decode and parse the payload knowing only the multicodec code.
> Add multicodec for DER-encoded X.509 certificate
